USE [master]
GO

/****** Object:  Table [dbo].[DEPARTMENT_DETAILS]    Script Date: 9/6/2022 5:13:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPARTMENT_DETAILS](
	[DD_ID] [nvarchar](10) NOT NULL,
	[Names] [nvarchar](30) NOT NULL,
	[Department_ID] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[DD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DEPARTMENT_DETAILS]  WITH CHECK ADD FOREIGN KEY([Department_ID])
REFERENCES [dbo].[DEPARTMENT] ([Department_ID])
GO

