USE [master]
GO

/****** Object:  Table [dbo].[ASSIGNED_TO]    Script Date: 9/6/2022 5:16:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ASSIGNED_TO](
	[Assigned_ID] [nvarchar](10) NOT NULL,
	[Time_Entry_ID] [nvarchar](10) NOT NULL,
	[RMS_ID] [nvarchar](10) NOT NULL,
	[SYSADMIN_ID] [nvarchar](10) NOT NULL,
	[ADMIN_DEPART_ID] [nvarchar](10) NOT NULL,
	[HR_ID] [nvarchar](10) NOT NULL,
	[ACCOUNTS_DEPART_ID] [nvarchar](10) NOT NULL,
	[Employee_Code] [nvarchar](10) NULL,
	[DD_ID] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[Assigned_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ASSIGNED_TO]  WITH CHECK ADD FOREIGN KEY([DD_ID])
REFERENCES [dbo].[DEPARTMENT_DETAILS] ([DD_ID])
GO

ALTER TABLE [dbo].[ASSIGNED_TO]  WITH CHECK ADD FOREIGN KEY([Employee_Code])
REFERENCES [dbo].[EMPLOYEE_TABLE] ([Employee_Code])
GO

